### ISSUE TITLE
Add `Portfile` to support MacPorts

### ISSUE THREAD

**Issue by marcransome** [marcransome/flog#38]
### Tasks to complete:

- [x] Create basic `Portfile` definition
- [ ] Add unit tests and update `cmake` configuration; see #46 
- [ ] Add test options `test.run`, `test.cmd` and `test.target` to `Portfile` accordingly; see `portfile(7)` for more information
- [ ] Update `Portfile` checksums to represent the latest [release](https://github.com/marcransome/flog/releases) tarball (`openssl dgst -rmd160 <file>` and `openssl dgst -sha256 <file>`)

**Comment by marcransome** [comment]
An initial `Portfile` definition has been added to a [forked ports tree](https://github.com/macports/macports-ports/compare/master...marcransome:macports-ports:master). Tasks remaining:

* Tests will need to be added to the source code in this repository, along with `cmake` configuration updates (i.e. `CTest` test definitions)
*  The test options `test.run`, `test.cmd` and `test.target` will need to be added to the `Portfile` definition accordingly. See `portfile(7)` for more information.

**Comment by marcransome** [comment]
An initial `Portfile` definition has been added to a [forked ports tree](https://github.com/macports/macports-ports/compare/master...marcransome:macports-ports:master) to add support for [MacPorts](http://macports.org).
